### ISSUE TITLE
Allow entering api keys on settings page?

### ISSUE THREAD

**Issue by jspaine** [freeCodeCamp/pantry-for-good#124]

**Comment by sherlyc** [comment]
is this done?

**Comment by jspaine** [comment]
No, I'm not sure its worth it any more. I wanted it to be really easy to deploy but the email is going to be pretty technical to set up anyway.

I don't know if we should eventually move the google maps keys from the settings page to env vars instead for consistency?

**Comment by mattmcsparran** [comment]
Can nodemailer be used instead of the current email API? Or is the email option used for more than password resets?

**Comment by jspaine** [comment]
There are several email types (some should really be replaced with a notification system), what difference does that make?

I looked into nodemailer because it would have been nice if you could just choose whatever email provider you want to use. But the heroku sendgrid addon gives you, I think, 12,000 emails a month for free which is probably good enough in most cases, though it requires setting up an api key so I don't think it would work well with nodemailer.

**Comment by mattmcsparran** [comment]
The only reason I asked was because I've used nodemailer on some applications of my own for password reset, and I knew it worked well/ would be easy to deploy for the purpose of password reset. I haven't tried with mass emails (which I'm not even sure if this application does mass emails).

**Comment by jspaine** [comment]
Ah ok, I meant difficult to set up for sending verified emails (that show as being from name@your-domain.com). I think you need to add a heroku ssl addon, set up dkim, maybe some dns configuration. If you can do that then just setting config vars from the heroku dashboard should be no problem.
