### ISSUE TITLE
Driver and food bank locations should be updated when the address is changed

### ISSUE THREAD

**Issue by jspaine** [freeCodeCamp/pantry-for-good#132]
This is implemented for customers as a mongoose pre-save hook and can probably be done similarly. Note the `submitValidate` meta tag is set in `saveCustomer` in the customer reducer to enable redux-form submit validation.

**Comment by ronaldblanco** [comment]
Hey I think I can help you here.
Give me a little more of detail.

**Comment by jspaine** [comment]
Hi, look at the customer model and you'll see the pre-save hook with the geolocation code. There needs to be something similar in the settings and volunteer (for drivers) models.

**Comment by ronaldblanco** [comment]
I will be working on this.

**Comment by ronaldblanco** [comment]
Hey I was checking the "Route Assignment" option on the staging branch and the bottom "Suggest Route" it is not working!
So, the objective of this issue is to have the location information (lat and lng) also on Volunteer and Settings models right??

**Comment by jspaine** [comment]
I can't check it at the moment, but don't see any reason it would be broken. There's a limit of 23 stops (21 customers) for calculating a route with google though, maybe that's the problem?

They have location info because the database is seeded with it, it's just not updated when addresses are changed and it needs to be.

**Comment by ronaldblanco** [comment]
Hey I did a pull request to this issue; check it and let me know if something must be change.

Thanks.

**Comment by ronaldblanco** [comment]
Hello Jspaine;
Is it a problem with the solution to this issue?

**Comment by jspaine** [comment]
Hi, I didn't actually revert it, I thought about it because the linter was failing due to unused variables and a forgotten import of ValidationError in `pre-save-functions.js`, so nobody could commit because it requires that it passes. And now I'm not sure how to remove that commit, or even where it is - it doesn't seem to exist on the staging branch.

I fixed the errors and tidied it up a bit instead, you can see what I did here - https://github.com/freeCodeCamp/pantry-for-good/pull/228

I know the tests weren't working on windows, but it should be fixed now. So if you disabled the precommit hook can you reenable it? It's also helpful to have eslint run in your editor so you can see the errors live, see if there's a plugin for yours.

**Comment by ronaldblanco** [comment]
Ok, I will be searching for a eslint module or pluging.

**Comment by ronaldblanco** [comment]
I am sorry for the inconvenience.

**Comment by jspaine** [comment]
It's fine, wasn't hard to fix :smile:
