### ISSUE TITLE
Clicking treeview (expandable) sidebar item sets it to active

### ISSUE THREAD

**Issue by jspaine** [freeCodeCamp/pantry-for-good#133]
Even though the current page hasn't changed.

**Comment by ronaldblanco** [comment]
Hello jspaine;

Could you please tell me what page and option are you referring to in the system and how can I help you fixed??

Thanks.

**Comment by jspaine** [comment]
Hey, on the sidebar when signed in as admin.
1) If you click say Customers so the route is customers/list the Customers menu item shows as active. If you then click Delivery, the delivery menu opens and gets set as active, even though the route hasn't changed.
2) If you choose say Drivers from the Delivery menu and close the Delivery menu, it gets set inactive even though the current route is a delivery route.

I think the easiest approach to fix the first issue is to make it so clicking an expandable menu item changes the route to the first subitems route.

The second I'm not sure, maybe you'd have to remove the AdminLTE event listeners and handle it all with react to really make it work properly. But I don't think it's as important so if you can just fix the first part it would be much better.

**Comment by ronaldblanco** [comment]
Hello jspaine;

Could you give and idea which file or files are the ones that need to by modified here for this problem and the first solution you are suggesting?
I am having a hard time finding it the more close I think is /modules/core/component/Sidebar/SidebarMenuItem.js
But I have done no progress.

Thanks.

**Comment by jspaine** [comment]
Yeah look at that and the menu is defined in `client/modules/core/reducers/menu.js` (you can ignore `clientItems`, they're for the top nav bar. the sidebar items start at line 114). 

Items with type `treeview` have a link property that will have to be the same as the first subitems link, so `settingsItems` is fine but the `link` in `deliveryItems` should be changed to `drivers/list`.

Then in the SidebarMenuItem component you have to make it so clicking the item changes the url. Try setting the href on line 11 to item.link. If it works you'll have to change the anchor tag to a Link component so the page doesn't reload.

**Comment by jspaine** [comment]
Alternatively, render the sidebar outside React, [something like this](http://tech.oyster.com/using-react-and-jquery-together#jquery-inside-a-react-component), and let AdminLTE handle the active/collapsed states. Then render a connected react component inside each list item to update the router state when clicked.

Anyone got any other ideas?

**Comment by ronaldblanco** [comment]
I will check your last suggestion; the previous one did not work on my tests.

**Comment by jspaine** [comment]
I'm not sure how clear I was there, you shouldn't have to do the first paragraph. I tried a bit like the second paragraph and couldn't get it to work.

**Comment by ronaldblanco** [comment]
Well I did look I little bit of the first paragraph but it was to deeper for me.
I did try all the changes on menu.js and SidebarMenuItem.js but it does not redirect to the href on the treeview element (as theoretically should)
I tried it using the <a> element and also changing it to a <link> element but always the behave is the same.

**Comment by kristoferma** [comment]
This issue seems to be a bug in the AdminLTE. I took a look at the newest version of the AdminLTE https://adminlte.io/themes/AdminLTE/pages/widgets.html and it seems to work correctly there.

I will try to update the AdminLTE files and see if that fixes the issue.
