### ISSUE TITLE
uploading logo/signature should create new files and delete the old ones

### ISSUE THREAD

**Issue by jspaine** [freeCodeCamp/pantry-for-good#152]
and update the media collection

**Comment by sherlyc** [comment]
would be happy to look into this.

**Comment by sherlyc** [comment]
noticed that if I try uploading a favicon file, it would render 3 undefined images which caused an error, is it a known issue?

**Comment by jspaine** [comment]
I hadn't noticed, looks like I forgot to register the field with multer (`server/routes/media`)
