### ISSUE TITLE
Saving a client should update all linked fields 

### ISSUE THREAD

**Issue by jspaine** [freeCodeCamp/pantry-for-good#153]
eg if a user is a customer and volunteer, saving the customer model should update the address in the volunteer model too

**Comment by ronaldblanco** [comment]
I would like to help in this!

**Comment by jspaine** [comment]
Ok, I'll explain a bit how it works:

Users can have 'client' types of customer, donor, volunteer, all with the same id as the user. So if user 10025 is a customer and donor there will be a customer model with id 10025 and a donor model with id 10025.

The client type models have a `fields` array containing fields defined in the questionnaire model for that client type. And linked fields are fields with the same id present in more than one questionnaire.

So a users customer model might have
```
fields: [{
  meta: 42deb211...    //ref to 'Street' in the customer questionnaire
  value: '234 W 42nd St'
}, {
  meta: 1ae2d550
  value: 'something customer specific' 
}]
```
and their donor model:
```
fields: [{
  meta: 42deb211...    //ref to 'Street' in the donor questionnaire
  value: '234 W 42nd St'
}, {
  meta: dd3d9beb
  value: 'something donor specific' 
}]
```
It's a bit tricky, let me know if you need anything.

**Comment by ronaldblanco** [comment]
I will be working on this.
I let you know if I need more info!

Thanks

**Comment by ronaldblanco** [comment]
Hello jspaine;
I am having problems making and update of information in the Donors page of the application for the staging branch, it is like in an infinite loop, this problem have prevented me of code on the donor controller (I can not test it) 
Is it something wrong with this functionality?
For this issue, do I must ignore the donor client type?
Until now I have been working on customers and volunteers only.

**Comment by jspaine** [comment]
I'd have to see some code to know what's wrong, make a [gist](https://gist.github.com/) and we can talk about it there.

It should work for all client types, but you can just do one to start.

**Comment by ronaldblanco** [comment]
I did create a gist:
https://gist.github.com/ronaldblanco/6dde20f69ef51f0fd019916803b1bcd3.js
In that case I will make a pull request with the code I have done to customers and volunteers only so you can check it.

**Comment by jspaine** [comment]
Ah I thought it was a problem with your code. Yeah seems donor update is broken, I'll look into it.

**Comment by ronaldblanco** [comment]
Yes, it is in the staging branch of the project (no changes on it)
I did a pull request with the code I have working in customers and volunteers; let me know if a must fix something.
