### ISSUE TITLE
alerts to show errors/success

### ISSUE THREAD

**Issue by jspaine** [freeCodeCamp/pantry-for-good#154]
react-s-alert looks ok and is also used by react-bootstrap-table (in v4, and i'm not sure we need alerts from tables)

**Comment by DavOnGit** [comment]
Can i help?

**Comment by DavOnGit** [comment]
Hi @jspaine can i take this?
Which actions should trigger the s-alert?

**Comment by jspaine** [comment]
Hi, I was thinking it could be useful for eg. 
- errors in forms, some are quite long (customer edit) and when you submit with an error the error can be hidden above the visible area
- the settings form doesn't have any indication that saving was successful
- probably some other places I can't think of right now

But I'm not sure now an alert would be a good way to improve these, think it could be a bit annoying and there are more subtle ways to do it, like for the two examples to just show a message close to the submit button. What do you think?

**Comment by DavOnGit** [comment]
Well they can be useful (if not abused) expecially in small screens where the keyboard may hide messages close to submit button.
They are a nice way to 'dispatch' key informations to users (like on save_success or delete_success actions) also if the router location changes, eg. when user updates details or when admin saves edits on customer application form.

**Comment by jspaine** [comment]
The keyboard on my phone closes when I click submit. But maybe you wouldn't see alerts that often with normal use of the app. And either way's going to be better than it is now.

**Comment by DavOnGit** [comment]
Hi @jspaine !
I deployed the app with s-alert on heroku: [link](https://pantry-for-good-notif.herokuapp.com/).
Code on this github repo: [link](https://github.com/DavOnGit/pantry-for-good/tree/feature/s-alert).

- Notifications are triggered from a new redux middleware file _alert.js_ (there is a better option?)
- s-alert react component is in _router.js_
- s-alert CSS is imported in _app.js_
- custom CSS added in _Application.css_ (dealing with z-index and harmonize colors)
- the animation is _flip_

As you suggested, the notification only shows on submitting forms with errors or on settings saved.

**Comment by jspaine** [comment]
> redux middleware file alert.js (there is a better option?)

It does feel a bit weird for that to be in a redux middleware, on the other hand it's kind of nice that all the alerts are defined in one central place... I'd import the action type from the settings reducer rather than use the string but it's not a big deal.

I'd put the alert component in the Application component, it should be pretty much top-level and has nothing to do with routes.

Why the naming `notifXx`? You save 1 letter over `notifyXx`

Otherwise it looks good!

**Comment by DavOnGit** [comment]
Ok, all done:
- _action type_ imported
- component moved to `Application.js`
- notifXx renamed to notifyXx (naming has always been hard for me :) )

**Comment by DavOnGit** [comment]
Should I PR this?

**Comment by jspaine** [comment]
Oh, yeah sorry I forgot! Go for it.
