### ISSUE TITLE
Disable 'Mark Packed' button when no checkboxes are selected

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/Pantry-for-Good#166]
On the Packing List page, if there are items in the packing list, and none of them are checked, then the packing list button should be disabled.

Note: The react component for this is defined in `client/modules/food/packing/PackingList.js`  This should be able to be fixed just looking at this one file.

**Comment by sherlyc** [comment]
hi Kenji, I would love to look into this.
