### ISSUE TITLE
Problem Following the Readme until: "npm run dev" command

### ISSUE THREAD

**Issue by ronaldblanco** [freeCodeCamp/pantry-for-good#189]
When I run "npm run dev" the server does not start and I have the error info as follow:

error Linux 4.9.17-c9
7 error argv "/home/ubuntu/.nvm/versions/node/v6.11.1/bin/node" "/home/ubuntu/.nvm/versions/node/v6.11.1/bin/npm" "run" "dev"
8 error node v6.11.1
9 error npm  v3.10.10
10 error missing script: dev
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by ronaldblanco** [comment]
'npm start' Works perfect!

**Comment by ronaldblanco** [comment]
Unable to login with:
admin@example.com
password

**Comment by jspaine** [comment]
Sounds like you're not on the staging branch, try `git checkout staging` then `npm run dev`.

How did you clone it? Staging is the default branch and if I clone a fresh copy I end up on staging. Wondering if the readme needs a note about it.

**Comment by ronaldblanco** [comment]
Hello I just did a fork of the project as was instructed.
It is like there are two deferents read me.

For me it is first time in contributing.

**Comment by jspaine** [comment]
There are 2 different readmes in 2 branches. The master branch hasn't been updated in some time so you need to make sure you're on the staging branch to start with.

If you run `git branch` from the project directory it should show the current branch as staging with a '*':
```
> git branch
  master
* staging
```
If it shows master as the current branch you need to switch to staging with `git checkout staging`.

You can also check the [contribution guide](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/CONTRIBUTING.md) for step-by-step instructions.
