### ISSUE TITLE
Set the copyright year to current year

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#199]
In the footer to the website, the **copyright 2016** is hard coded.  Change it so the year is set programmatically to the current year.  The footer is a react component in the file
`client/modules/core/components/Footer.js`

**Comment by dmcfaddengalway** [comment]
I'd like to this issue up! Let me know if this is okay.

**Comment by dmcfaddengalway** [comment]
Made the required changes and have made a PR, followed the Contributing guidelines and such

**Comment by dmcfaddengalway** [comment]
Just made the changes, let me know if this is more of what you want.

**Comment by kenjiO** [comment]
PR #201 closed this issue
