### ISSUE TITLE
Packing Modal add item button UI improvement

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#200]
On the packing page, if you click the blue 'Pack' button it brings up a modal to select items to pack.  It would be good to have the 'Add Selected Food' button set to disabled when the user has not yet selected a food in the select box.  The modal is defined in the file `client/modules/food/components/packing/PackModal.js`
To check if anything is selected in the select box check the value of `this.state.otherItemSelectBoxValue`

**Comment by dmcfaddengalway** [comment]
I'd like to take this issue up. It's my first time contributing to OSS but I'd be glad to help if I'll have a community to support me!

**Comment by kenjiO** [comment]
Please go ahead to work on it and let us know if you need any help with anything.

**Comment by benwh1te** [comment]
First time contributing. Noticed this was still open and unfixed. I have a fix ready but am unable to commit. The tests scripts are failing.  `Warning: Could not find any test files matching pattern: 'client/**/*.spec.js'
No test files found`
I'm not sure if I am not set up correctly or if this is a bug that needs fixing.

**Comment by jspaine** [comment]
That's weird, any idea what the problem was?

**Comment by benwh1te** [comment]
Not sure. The files were definitely there. I got around it by removing the pre-commit check and committing the change I needed. Not good practice I know, but I'll be sure to find out what the issue is.

**Comment by jspaine** [comment]
Think it might be the globs, are you on windows/not using a bash shell? Can you try with git-bash or something?

**Comment by benwh1te** [comment]
I'm using git-bash. I'll look at the configurations and see if I can fix anything

**Comment by jspaine** [comment]
Should be fixed now, seems the single quotes don't work on windows.
