### ISSUE TITLE
Google Sign Up/Sign In

### ISSUE THREAD

**Issue by ajGingrich** [freeCodeCamp/pantry-for-good#202]
This may have already been addressed, but I had trouble initially with the app because I was trying to "sign-in" with google for the first time instead of "sign-up". I thought my oauth or credentials were messed up. 

If it makes sense for everybody else but for me, that's fine close it right away. But if not, I thought it could be helpful to immediately sign in & sign up for user experience.

**Comment by jspaine** [comment]
Yeah I think that would be much smoother too.
