### ISSUE TITLE
Problems Setting Up Local Installation on Windows 10

### ISSUE THREAD

**Issue by wwSchrader** [freeCodeCamp/pantry-for-good#211]
Hi Everyone!

I was trying to do a local installation on my Windows 10 computer, but I ran into 2 issues:

First: 

The package.json scripts for the dev doesn't work in a Windows 10 environment. It threw a:

> "'NODE_ENV' is not recognized as an internal or external command, operable program or batch file."

It was coming from this line:
`"scripts": {
     ...
   "dev": "NODE_ENV=development gulp watch",
   ...
}`
I had to set it to this to make it work:
`"scripts": {
     ...
  "dev": "SET NODE_ENV=development & gulp watch",
   ...
}`

Second:

Once I made the above changes, I was getting this:

> Error: Cannot find module './env/development '

I tracked the problem down to the ./server/config/index.js to this line:
``require(`./env/${env}`).default,``
I could only make it work by hard coding the path:
`require('./env/development').default,`
Everything worked fine after that.

So is there a more elegant solution for us Windows users to install this?

**Comment by jspaine** [comment]
Hi, thanks for the heads up! We have a contributor on windows so I thought it worked.

Can you pull the latest change, npm install and try it?

**Comment by wwSchrader** [comment]
That did the trick. Thank you!
