### ISSUE TITLE
Implement session timeout

### ISSUE THREAD

**Issue by jasonsreynolds** [freeCodeCamp/pantry-for-good#22]
Implement automatic session expiration, in accordance with OWASP. See https://www.owasp.org/index.php/Session_Management_Cheat_Sheet#Session_Expiration

**Comment by Rusticman** [comment]
Hi Jason,
             For further clarification - do you mean after 10 minutes of inactivity by the user? Or simply logout after 10 minutes of use?

The latter is fairly straight forward, the other requires a client-side function that monitors inactivity. I'm happy to tackle this either way.

**Comment by DealPete** [comment]
Hi Rusticman,

I updated the issue to be clearer. The sort of scenario we're imagining is this - A user uses our web site at a library computer, doesn't log off and leaves. Someone else sits down, notices the website open, and starts poking around. We want the server to automatically end the session after a certain fixed period of inactivity.

**Comment by sherlyc** [comment]
would be happy to look into this.

**Comment by sherlyc** [comment]
noticed you have
`const user = await User.findById(_id, '-salt -password')`
at the passport.js
where your User is :
`import User from '../models/user'
`
However when I go to models/user.js, I can't find any function or any method that goes by the name of findById in there.

Sorry for the trouble, I'm studying the code before I could work on it.

**Comment by jspaine** [comment]
No problem, User's a mongoose model, so it's defined by mongoose. If you haven't tried vscode or something with intellisense I'd really recommend it.

**Comment by ZackWard** [comment]
@sherlyc Are you working on this? If not, I would be happy to help with it.
