### ISSUE TITLE
Deleting food items that exist in a package causes reference errors

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#220]
If you add a food item to a package and pack the package, then go to the inventory and delete the food item, then go back to the package listings the food name will not show in the package contents and there will be an error in the console since the food item ID in the package no longer references anything.

**Comment by kenjiO** [comment]
I thought of two ways of fixing this.

1.  Instead of deleting food items from the database, set a property to indicate they are deleted. Then any data that keeps a reference to that ObjectID can still get the data for it.   This requires filtering out items marked as deleted when querying food items. 
[example](https://github.com/kenjiO/Food-for-Good/commit/a90f25352fd7329993d8d4c0a558234c6f8b9ccb)

2. In the packages mongoose model store the necessary data for the food Items.  So even if the food item is deleted the package entry won't depend on it to get the name of the food item.
[example](https://github.com/kenjiO/Food-for-Good/commit/0a766cc7346c1b57dec4c220499d43cb13d6b134)

@jspaine do you have any thoughts on which would work better or if there is another way you would do it?  There are also some fields in the customer food preferences that store food item IDs.  And for any of the other models that store ObectIDs of things that could be deleted this would be an issue too.

**Comment by jspaine** [comment]
Hmm, 2 sounds the easiest, if you only need to store the name as well the extra space is going to be negligible.  Would only be an issue anyway if there were thousands of customers and running for many years. Maybe the biggest problem is that renaming an item isn't going to be updated in the packages unless you do it manually, and packages is going to be the biggest collection.

I'm starting to lean towards 1. Items shouldn't be that numerous, and deleting them shouldn't be that common so sending and filtering won't be really expensive. I always feel I'm using mongo wrong though by keeping things normalized, I guess at the scale of this app it doesn't really matter.

Yeah the food controller currently adds newly added items to all the customers food preferences, which doesn't seem like something you'd want to do. Should probably be changed to instead delete from all customers food preferences when the item is deleted.

**Comment by kenjiO** [comment]
I like the first way a little bit better too.  I will continue to work on that example and make it into a complete fix for it.
