### ISSUE TITLE
Add Cusomer name to Packing List

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#222]
On the Packing List page add a column to the **Packing List** and **Packed Packages** tables next to the Customer ID that displays the Customer Name.

**Comment by benwh1te** [comment]
I would like to take this issue.

**Comment by kenjiO** [comment]
Thanks for helping with this issue benwh1te.  If you have any questions please post them in a comment here.

**Comment by benwh1te** [comment]
Just finished up will do a PR soon.
