### ISSUE TITLE
/users/profile page getting 403 errors for users without a role

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#232]
All user accounts used to be created with an initial role but now user accounts are not assigned a role initially.  For any user without a role trying to go to the /users/profile page will get a 403 unauthorized error.

In client/modules/user/UserRouter.js the route for 'profile' should test for a logged on user and not for a valid role.

**Comment by davycheung** [comment]
Added a PR #237

**Comment by nodox** [comment]
Probably should close this issue.
