### ISSUE TITLE
Donation Values Treated as Strings

### ISSUE THREAD

**Issue by davycheung** [freeCodeCamp/pantry-for-good#243]
Looks like the donation values are being concatenated instead of being summed up.

<img width="611" alt="screen shot 2017-09-21 at 9 59 03 pm" src="https://user-images.githubusercontent.com/4220987/30726394-8f472086-9f18-11e7-9485-b59f2338b6ce.png">
<img width="1017" alt="screen shot 2017-09-21 at 9 59 34 pm" src="https://user-images.githubusercontent.com/4220987/30726397-913c0c30-9f18-11e7-86f5-c0a434175c5e.png">

**Comment by cjhaviland** [comment]
I am just getting my local instance setup but I'd like to take a crack at this if no one minds.

**Comment by ik226** [comment]
just saw this comment.. I have just made PR on this. Can you please look into it and let me know if you have other approaches to fix this issue? Thanks!

**Comment by jspaine** [comment]
Yeah that looks fine. Sorry @cjhaviland, hope you can find something else you'd like to try.

**Comment by cjhaviland** [comment]
I think wrapping it in a number should be fine, but like I said I haven't gotten a chance to get everything up and running yet to look. I would definitely check that there is validation on the input so we can only accept numbers.

**Comment by jspaine** [comment]
The value input on the client and the mongoose schema are both type number. Not sure why this is a problem, and only with user entered data (seems fine with seed data).

**Comment by ik226** [comment]
I believe that redux-form is returning values as string. (In components/DonationCreate.js, we are converting item.value to Number in order to calculate total item amount due to this reason).

**Comment by kenjiO** [comment]
I think it would make the backend more robust not to assume that the `item.value` property is going to be a number.  If another api client is ever used or something breaks the validation in the front end it would be good for the server to handle something that can't be converted to a number.   Maybe
change  `(acc, item) => acc + Number(item.value)` to something like
```javascript
(acc, item) => {
  // TODO:  check if Number(item.value) is NaN.  If so throw BadRequestError
  return acc + Number(item.value) 
}
```

**Comment by kenjiO** [comment]
We still need to validate that the value properties for the items are numeric on the server.  If anyone ones to take this please leave a comment.

**Comment by logangingerich** [comment]
I should be able to work on this over the next few days!
