### ISSUE TITLE
[question] Do sub categories exist?

### ISSUE THREAD

**Issue by Knochenmark** [freeCodeCamp/pantry-for-good#244]
I am wondering if there exists something like sub categories.

For example something like:

- Milk products
  - Milk
     - Milk
     - Soymilk
  - Cheese
    - Gouda
    - Cheddar
  - Yogurt
    - Strawberry
    - Vanilla

Maybe you could nest these categories even deeper depending on what products.

**Comment by jspaine** [comment]
It doesn't at the moment. But it would be quite a big job to implement and I'm not sure there's really a need. @jasonsreynolds what do you think? How many products does yours stock?

**Comment by kenjiO** [comment]
I agree that for now it would be better to hold off on implementing this. I think the following would be a higher priority to implement

- being able to specify quantities of food items when making packages
- the ability to make a package that is not scheduled
- creating reports or charts
- being able to mark packages as delivered or picked up by a client
- being able to import or export data from a file such as an excel spreadsheet
