### ISSUE TITLE
Errors thrown in async controller functions not being caught in express error handler

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#252]
If an error is thrown in an async method in one of the express controllers the   `app.use(function(err, req, res, next) {} `function in `server/config/express.js` does not catch it.  It gets caught it the `process.on('unhandledRejection') `method in `server/server.js` and the client request times out with no response.  It should get caught in the express error handler so it can respond with an error code to the client.

Maybe something like [this](http://madole.xyz/error-handling-in-express-with-async-await-routes/) will work

**Comment by jspaine** [comment]
express-promise-router does that. Looks like donation and api routes aren't using it.

**Comment by wacii** [comment]
I believe this was fixed in PR #286. The donation router was changed to use `express-promise-router` as suggested by @jspaine.

**Comment by kenjiO** [comment]
Yes, that PR fixed this issue. Thanks for pointing that out.
