### ISSUE TITLE
mongoose model defaults for foodItemSchema

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#262]
I think it would be more sensible to set the default frequency of the [foodItemSchema](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/server/models/food.js) to 1 (every week) instead of 0.  Also a default startDate of the current date makes sense to me.

**Comment by Todor46** [comment]
Hello! I'd like to contribute to this if I may 😄

**Comment by jspaine** [comment]
Hi, go for it! No need to ask, just say you're doing it and keep up updated.

**Comment by icpmacdo** [comment]
https://github.com/freeCodeCamp/pantry-for-good/pull/265

I might have made this pr incorrectly

**Comment by Sirmorrison** [comment]
Did like to contribute but really not clear on what the issue is yet

**Comment by jspaine** [comment]
There's already a pull request in to fix it, sorry. If you need any help with another issue just leave a comment there.

**Comment by Sirmorrison** [comment]
Did like to contribute but really not clear on what the issue is yet

**Comment by Thirdoptics** [comment]
First time jumping into a larger project, but I believe pull request [#267](https://github.com/freeCodeCamp/pantry-for-good/pull/267) fixes this.  Please let me know if I've misstepped or missed something in jumping in and contributing.
