### ISSUE TITLE
Reset password page not handling server errors

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#271]
To replicate go to http://localhost:8080/users/reset-password/xxxxxx, enter a new password and verification and click the button.  An xhr request is made and the server returns an error that the token is invalid but the web page does not display the error and still displays the loading spinner.

This also needs to be fixed on the **/users/forgot-password** page.  If you enter an invalid email the same behavior happens.

**Comment by prabhu-08** [comment]
@kenjiO I would like to work on this. Please assign it to me. Thanks.

**Comment by kenjiO** [comment]
It's all yours.  Thanks for helping out.

**Comment by prabhu-08** [comment]
@kenjiO as of now raised a PR with second solution #283 & #284 . Let me know if this is fine.

**Comment by kenjiO** [comment]
I think it's better not to change to LoadingWrapper functionality to also show error messages.  I will merge the PRs with the second solution.  Thanks for the fix.
