### ISSUE TITLE
When changing customer status to inactive it sends the rejection email

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#272]
When an admin changes the status of a customer to inactive, the server sends the rejection email to the customer.  It should only send the rejection email when the status is changed to rejected.

**Comment by prabhu-08** [comment]
@kenjiO I would like to work on this. Please assign it to me.

**Comment by kenjiO** [comment]
OK, it's all yours prabhu

**Comment by prabhu-08** [comment]
@kenjiO Raised a PR #288  for this. Let me know if this is fine.
