### ISSUE TITLE
validation fails after editing customer info 3 times

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#273]
If you are a customer that has already applied, if you try to edit details for the customer application more than 2 times it will get a validation error saying "address not found" even if it is a valid address.  Refreshing the page in the browser fixes this but the user should not be required to refresh the page.

**Comment by thmsdnnr** [comment]
Hey kenjiO,

Could you throw in more steps to reproduce or maybe the text + a screenshot of the error? Do you get any console log information when the error occurs?

I ran into an issue where I got screenshots like this after editing 2-3 times with the current codebase: ![image](https://user-images.githubusercontent.com/18345212/32608487-23d3b168-c522-11e7-8675-4147dd674553.png). 

The error went away when I made the fix from https://github.com/freeCodeCamp/pantry-for-good/issues/310. Maybe the same issue, or maybe another one!

**Comment by kenjiO** [comment]
#311 fixed this
