### ISSUE TITLE
Alphabetize the category list on the inventory page

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#277]
It will be easier to find categories if they are in alphabetical order.  

I think if the `map` function is called on a sorted copy of `this.props.foods` in [this function](https://github.com/freeCodeCamp/pantry-for-good/blob/297cf2035ad7c6d8d4498af34848c04d2082aa9f/client/modules/food/components/inventory/FoodCategories.js#L30-L38) it should list them alphabetically.

**Comment by Bubblemelon** [comment]
Hi @kenjiO , I would like to help :) I have not contributed to freeCodeCamp before.

**Comment by kenjiO** [comment]
Thanks for your interest in helping out.  Please go ahead and implement this and put in a pull request for it.  If you have any questions or need help please post a comment here.

**Comment by kenjiO** [comment]
@Bubblemelon, can you let me know if you are still working on this or need any  help on it?

**Comment by Bubblemelon** [comment]
Hi @kenjiO, my apologies I have almost forgotten about this. Do you mind walking me through this so we're on the same page? Are you saying that [this function](https://github.com/freeCodeCamp/pantry-for-good/blob/297cf2035ad7c6d8d4498af34848c04d2082aa9f/client/modules/food/components/inventory/FoodCategories.js#L30-L38)'s output is not in alphabetical order? Also, do I need to install pantry for good or am I missing something important in [the function](https://github.com/freeCodeCamp/pantry-for-good/blob/297cf2035ad7c6d8d4498af34848c04d2082aa9f/client/modules/food/components/inventory/FoodCategories.js#L30-L38) that I'm not seeing. Please enlighten me. Thank you!

**Comment by kenjiO** [comment]
`this.props.foods` is not in alphabetical order and the `getTableRows` function does not do anything to sort it.  I think it would be best to sort the elements in `this.props.foods` into a new array and then call the `map` function on the new array of sorted foods.

You should definitely setup the application on your computer if you want to work on it.  Please follow the instructions in [CONTRIBUTING.md](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/CONTRIBUTING.md) to fork a copy of the repository to your github account and setup the application locally on your computer.

**Comment by agoncecelia** [comment]
I wanted to fix this, but the food categories are already sorted alphabetically. Check it again if i may be mistaken?

**Comment by jspaine** [comment]
It's sorted to begin with, but if you add a category it just goes at the bottom.

**Comment by Bubblemelon** [comment]
Hi ! Thank you for being patient 😄 

Here's the edit I made: 
[https://github.com/freeCodeCamp/pantry-for-good/pull/355](https://github.com/freeCodeCamp/pantry-for-good/pull/355)
