### ISSUE TITLE
Broken driver routes list CSS

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/pantry-for-good#291]
I was scrolling through the driver route and I saw some broken CSS. 

I'm using Chrome version 61.0.3163.100 (Official Build) (64-bit).

Here's what it looked like:

![routes_-_drivers_-_foodbank_template](https://user-images.githubusercontent.com/985197/32138847-d52d3de8-bbff-11e7-8752-0720d4180450.png)

**Comment by kenjiO** [comment]
I'm running the same version of Chrome on a Mac and the only time I get this is when I have the developer tools open.

**Comment by agoncecelia** [comment]
I am getting the same error in Firefox version 56.0 (32-bit).

I want to try and fix this.

**Comment by QuincyLarson** [comment]
@kenjiO I am still getting this even without the devtools engaged. 

![routes_-_drivers_-_pantry_for_good_and_halt_and_catch_fire_s03e10_mp4_-_mpv](https://user-images.githubusercontent.com/985197/32288975-79f7c932-bf03-11e7-91f5-26e88e6d379f.png)
