### ISSUE TITLE
Runtime error on build  '7c35c49'

### ISSUE THREAD

**Issue by sneh1** [freeCodeCamp/pantry-for-good#293]
Today I updated my code to the latest staging build '7c35c49'
[npm-debug.log](https://github.com/freeCodeCamp/pantry-for-good/files/1425177/npm-debug.log)

 and I am got error 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
```

Please check the attached log for additional details.

**Comment by jspaine** [comment]
It works for me, looks like it's already running. Try to close any running node processes and `npm run dev` again.

**Comment by sneh1** [comment]
worked. thanks @jspaine
