### ISSUE TITLE
Assign customers UI improvement

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#294]
On the Route Assignment page, I think it is confusing how it says Customers and then has the dropdown box with the driver name.  

![screen shot 2017-10-30 at 1 36 18 pm](https://user-images.githubusercontent.com/5035181/32194420-952f6e36-bd77-11e7-9465-5742c8bab6bf.png)  

In this example it looks to me like Neha Mayert is the customer.  I think we should change "Customers" to "Customers assigned to driver" or do some other change to the UI to make it more intuitive that what you are doing is using the select box to select a driver and listing the customers assigned to the driver selected.

**Comment by logangingerich** [comment]
I should be able to put something together for this in the next few days!

**Comment by Crowes** [comment]
Isn't that empty table also a waste of whitespace when entirely empty? It's not much of a visual cue. I'm thinking something similar to Bootstrap's `.alert-danger` would suit.
