### ISSUE TITLE
Format the dates on the Packing List page

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#299]
On the Packing List page the **Last Packed On** and **Date Packed** columns show dates like this **2017-10-30T18:37:14.553Z**.  It would be nice to have them in an easier to read format like 10/30/2017

**Comment by Dataster** [comment]
is it ok if I work on this?

**Comment by kenjiO** [comment]
Yes, please go ahead.  If you have questions or need help please post a comment here

**Comment by Dataster** [comment]
Thanks. I have gone through the setup instructions and downloaded the code creating a local Git repository. Also, able to compile / run the app in DEV mode locally. 

Will start to look at the code now.
