### ISSUE TITLE
Schedule and Inventory access restrictions

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#303]
If you create a volunteer account you can view data by going to these URLs
http://localhost:8080/schedule
http://localhost:8080/inventory

This data should only be accessible after an administrator has assigned the roles/inventory or roles/schedule to a volunteer.

**Comment by agoncecelia** [comment]
I tried fixing this by adding the hasAuthorization method from foodController in the GET method as a parameter. It works but it is not passing the tests.

 1) Food Api User routes lists food categories:
     AssertionError: expected { message: 'User is not authorized' } to be an array
      at D:/pantry-for-good/server/tests/integration/food.spec.js:45:34
      at Test._assertFunction (node_modules\supertest\lib\test.js:281:11)
      at Test.assert (node_modules\supertest\lib\test.js:171:18)
      at Server.assert (node_modules\supertest\lib\test.js:131:12)
      at emitCloseNT (net.js:1558:8)
      at _combinedTickCallback (internal/process/next_tick.js:77:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by jspaine** [comment]
Customers have to be able to GET foods to edit their food preferences, is why you're getting that error. I think one hasAuthorization function isn't enough in this case. Could maybe split it into hasReadAuthorization, hasCreateAuthorization, hasUpdateAuthorization etc.

I think we want something like this

operation | roles
-|-
read | customers, inventory, schedule
create | inventory
delete | inventory? or just admin
update | inventory or schedule, then further checks in update controller so users with schedule role can only update schedule related fields

Admin should bypass all checks. Roles are defined in `common/constants.js`.

On the client it's pretty easy, in the main router (`client/Router.js`) the inventory, packing and schedule routes are allowed for volunteers, it should just be a matter of narrowing it down to the appropriate roles.
