### ISSUE TITLE
Changing customer status from Away to Available should not send an email

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#320]
To replicate:
1. logon as the admin user
2. Go to the list of customers
3. Find an accepted customer and click the pencil icon to edit
4. On the edit page click the Away button in the status section
5. Then click the Available button to to set status to Available

When the Available button is clicked it sends the "Customer Accepted" email to the customer.  It should only send this email when the customer has been changed from Pending to Accepted.

#288 was a really similar issue so the fix for that may be similar as well.

**Comment by yuzu-r** [comment]
I'd like to work on this issue.

**Comment by kenjiO** [comment]
Thanks for offering to help out with this yuzu-r.  If you have any questions or need help please post a comment here.

**Comment by alfonsotech** [comment]
Hi, I'd like to work on this as well. Want to pair program @yuzu-r?

**Comment by kenjiO** [comment]
@alfonsotech, feel free to work on this since there hasn't been any activity for 2 months.

**Comment by tsangb** [comment]
I took a look, and the issue appears to be in the "server/controllers/customer.js" file.
Specifically, the update method only checks for a difference between the old and new status, which is probably what causes the email creation.

My question is what you want the intended behavior to be.  Do we want the change of Away -> Available to send an email at all?  What are the cases where we want to send an email versus not?  This would change the truth statement in the following lines:

if (newCustomer.status !== oldCustomer.status) { 
  mailer.sendStatus(newCustomer)
} else {
  mailer.sendUpdate(newCustomer)
}

**Comment by kenjiO** [comment]
I think instead of using `newCustomer.status !== oldCustomer.status` we should do `oldCustomer.status === 'Pending' && (newCustomer.status === 'Accepted' || newCustomer.status === 'Rejected')`

I think the customer only needs to be emailed when their status is changed from Pending to either Accepted or Rejected (which is done by an administrator).  Changes to Away and Available are done by the customer themselves so there is no need to notify them by email.
