### ISSUE TITLE
UI Problem- Navbar dropdown icon is not at same height with navbar item

### ISSUE THREAD

**Issue by wildaces215** [freeCodeCamp/pantry-for-good#323]
<img width="240" alt="screen shot 2017-11-17 at 9 29 13 pm" src="https://user-images.githubusercontent.com/13178401/32976132-aaa46cb0-cbde-11e7-9909-88caf99161a0.png">

Operating System: Mac high Sierra 11.0
Browser: Mozilla Firefox

**Comment by kenjiO** [comment]
The arrow icon styles are defined [here](https://github.com/freeCodeCamp/pantry-for-good/blob/6bfe73416aa3aabef036d4505fbd51f32024e5d1/client/modules/core/css/core.css#L26-L34).  Maybe adjusting something in this selector will fix it.

**Comment by logangingerich** [comment]
I can definitely start taking a look at this, if nobody else is currently working on it.
