### ISSUE TITLE
possible issue with extend(user, req.body)

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#337]
https://github.com/freeCodeCamp/pantry-for-good/blob/686a83b1c3374b465d33c21d151a954163340ceb/server/controllers/users/profile.js#L30-L40

Is the `extend(user, req.body)` statement here a problem if someone changes the _id attribute sent with req.body or some other attribute of req.body? Except for the roles property, it looks like the user can send whatever they want as req.body and it will overwrite the req.user.

**Comment by wacii** [comment]
I don't know MongoDB well enough to say what all could happen, but regardless I would suggest whitelisting the keys you wanted to have updated. So something like this:

```js
extend(user, pick(req.body, ['email', 'firstName', 'lastName']))
```

**Comment by jspaine** [comment]
Yeah this is definitely a problem. Could also use omit if a model has lots of fields but only a few need to be restricted. Mongoose won't save any fields not defined in the schema.

It's going to be a bit annoying to keep things in sync if fields need to be added. Also some controllers might need to allow different fields depending on if the user is admin/other roles and could get a bit messy. Maybe the routes would be a better place to do it?
