### ISSUE TITLE
Add Customer Name to Packed Packages List

### ISSUE THREAD

**Issue by davycheung** [freeCodeCamp/pantry-for-good#352]
Would be useful to add the Customer name to the packed packages list. The customer column is currently only displaying the Customer ID. Good one for a first-timer. 

<img width="1276" alt="screen shot 2018-01-01 at 5 00 15 pm" src="https://user-images.githubusercontent.com/4220987/34471369-a09d3c1a-ef15-11e7-9c0b-3262d5d74134.png">

**Comment by sneh1** [comment]
I want to work on this.

**Comment by sneh1** [comment]
When I try to commit my change. I get error: `Fatal RangeError: Maximum call stack size exceeded`
It has also been discussed here: #130 
How can I commit my change, is there a workaround?

**Comment by jspaine** [comment]
You can add the `--no-verify` flag to `git commit` or `git push` to skip running the tests if you think the error's not related to your changes.
