### ISSUE TITLE
Packed package list create a 'contents' tool-tip

### ISSUE THREAD

**Issue by davycheung** [freeCodeCamp/pantry-for-good#356]
The "Contents" column on the packed packages list is not really useful. Their are usually a number of contents which are being cut off. Perhaps someone can scrap the text column and shift the contents into a modal that is activated by a button on the right most column next to "Unpack".

<img width="1273" alt="screen shot 2018-01-06 at 6 11 07 pm" src="https://user-images.githubusercontent.com/4220987/34644875-3f978b04-f30d-11e7-8255-464f73f1ae85.png">

**Comment by kenjiO** [comment]
I think if we could make some kind of tooltip with the contents that shows when the mouse hovers over that table cell it would be good.  Then the user doesn't have to click to open and close models and can easily run down that column with their mouse pointer to see the contents of each package.

**Comment by davycheung** [comment]
Sounds good!
