### ISSUE TITLE
Overlapping definition of 'roles' and 'accountType' for users

### ISSUE THREAD

**Issue by MAF27** [freeCodeCamp/Pantry-for-Good#37]
It seems that roles and accountType evolved side by side as the app grew, with overlaps and unclear division of labor between them. Roles can be 'user', 'customer', 'volunteer', 'driver', 'donor', or 'admin’. accountType can be 'volunteer', 'donor', 'customer', or ’admin’. 

The two should be separated, using roles for authentication (valid roles being ‘user’ or ‘admin’) and accountType for differentiating between clients, donors and volunteers.

**Comment by khawajah** [comment]
Hello...can i have more detail for this issue??!  thnx ^_^

**Comment by MAF27** [comment]
Hi - have you looked at the code and my description? Happy to answer specific questions if you have them.
