### ISSUE TITLE
'Unknown user or invalid password' should be displayed to the user, in case, while trying to Sign In

### ISSUE THREAD

**Issue by gomezvillegasdaniel** [freeCodeCamp/pantry-for-good#370]
https://pantry-for-good.herokuapp.com/users/signin
![unknown user or invalid password pantry for food](https://user-images.githubusercontent.com/6345953/37808504-518380be-2e10-11e8-9e9f-c2151a2e3cf6.png)

**Comment by gomezvillegasdaniel** [comment]
hands on it

**Comment by gomezvillegasdaniel** [comment]
@jspaine Hi, I don't find the SignIn response. I've inspected the
 this.props.signIn(this.state.email, this.state.password) call but it doesn't response anything. Could you help me pls?

**Comment by gomezvillegasdaniel** [comment]
ok, but I noticed that if I jump to the `auth/SIGNIN_FAILURE` with the redux devtools it already displays the error on the screen, so I think I need to know how to get the store from the component and see if the status response is 400, then jump to that state?

**Comment by kenjiO** [comment]
I think this is what is going on the way the application is now:

 Every time [UserRouter](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/client/modules/users/UserRouter.js) renders it calls [guestOrRedirect(SignIn)](https://github.com/freeCodeCamp/pantry-for-good/blob/9f2bdc261bb0abddb18ef00d1bad118cc9dbe3c9/client/components/router/guestOrRedirect.js#L23-L40).  This results in both the `GuestOrRedirect` and `SignIn` components getting unmounted, re-created and then mounted again which dispatches the `CLEAR_FLAGS` action. 

I think that we only want to have the GuestOrRedirect with SignIn component created one time.  So either changing [UserRouter](https://github.com/freeCodeCamp/pantry-for-good/blob/staging/client/modules/users/UserRouter.js) to not call this repeatedly or changing [guestOrRedirect](https://github.com/freeCodeCamp/pantry-for-good/blob/9f2bdc261bb0abddb18ef00d1bad118cc9dbe3c9/client/components/router/guestOrRedirect.js#L23-L40) to not create a new component each time should fix this.

**Comment by gomezvillegasdaniel** [comment]
Thanks, I've tried to singletonise the GuestOrRedirect class when the WrappedComponent is instance of SignIn, but the class is being redeclared each time the guestOrRedirect function is called, so I loss the singleton instance. I don't know any other way to do it.

**Comment by kenjiO** [comment]
I think moving the call to guestOrRedirect outside of the UserRouter function will fix this. 

```
const guestOrRedirectSignIn = guestOrRedirect(SignIn)

const UserRouter = ({match}) =>
 <SwitchWithNotFound>
    .
    .
    .
    <Route path={`${match.url}/signin`} exact component={guestOrRedirectSignIn} />
```

If this does work we will probably want to look at using it with the other routes calling guestOrRedirect and userOrRedirect if similar issues are happening with them
