### ISSUE TITLE
Issues with running on Windows 10

### ISSUE THREAD

**Issue by jagastro** [freeCodeCamp/pantry-for-good#377]
All,

I've been trying to get the code to run for a little while now, and I keep running into this issue:

![image](https://user-images.githubusercontent.com/25017251/40293379-839a1592-5c85-11e8-836e-3b0f5a7755cd.png)

From the ReadMe file, I can install npm just fine. The error seems to be in the event.js, line 183 code. I'm not sure whether I'm the only one experiencing this issue, or whether there's a fix I'm not aware of. Figured I'd mention this potential issue.

**Comment by jspaine** [comment]
Hi, it just means you have something already running on port 8080. You can stop it before running this, or change the port this uses (in https://github.com/freeCodeCamp/pantry-for-good/blob/staging/webpack.config.dev.js)

**Comment by jagastro** [comment]
Meant to close this issue much earlier--sorry for the delay!
