### ISSUE TITLE
secrets.js api keys not being integrated

### ISSUE THREAD

**Issue by ShelleySuhling** [freeCodeCamp/pantry-for-good#381]
I keep getting errors regarding missing api keys even when keys are added to `server/config/env/secrets.js`. 

This is the error I get when navigating to path `drivers/list`:
   ```Google Maps JavaScript API error: MissingKeyMapError```

My `secrets.js` file looks like this:
```  gmapsApiKey: process.env.GMAPS_API_KEY || 'API KEY HERE',``` replacing "API KEY HERE" with my personal google maps api key

I have been able to get the api to work when directly adding the key to the file `Maps.js`

Anyone else having this issue? Or know how I can fix it locally?

**Comment by kenjiO** [comment]
Can you try adding `console.log('gmapsApiKey is: ' + config.gmapsApiKey)` to the end of the file `server/server.js`.  Then try `npm run dev` and check the console to verify that it is picking up your API key from the config file.  If it is picking up your key can you post the error you get in your browser console.

**Comment by jspaine** [comment]
Sorry about that, this needs fixing somehow. The easiest was to add it for now is at the bottom of the general settings page.

The reason it's like that is the key is needed on the client (also not ideal) so it's kept in the database. And it's added there while seeding so doesn't get picked up from the environment after you've run it for the first time.

**Comment by ShelleySuhling** [comment]
Oh I had no idea that was even there! Could I make a PR updating the documentation?

**Comment by jspaine** [comment]
Yeah that would be good, thanks!
