### ISSUE TITLE
Continue the work

### ISSUE THREAD

**Issue by yzhbankov** [freeCodeCamp/Pantry-for-Good#59]
Hello Pete.
Why are you close all issues.
Are you close the project or the work will continue.
I was taking a break in working with food-bank-app to learn more about angularjs and when i have some progress i find that all the issues are closed.

**Comment by DealPete** [comment]
Hi yzhbankov,

We've actually decided to make the switch from Angular to React.js, as part of policy to have all Open Source for Good projects use React. Michael has assembled a team to do this work, and I've closed all the open issues to prevent code duplication. As parts of the application get implement in React.js, I'll start opening issues that don't conflict with the team's ongoing work.

Thank you for the work you've done for us so far. You've been very helpful. I expect that Michael will be in touch with you about how you can help going forward.

**Comment by jspaine** [comment]
I made some issues from the projects page, what do you think?
I tried to prioritize them so only added some, will try and have a look for more bugs.
