### ISSUE TITLE
Do we need the food schedule items start date?

### ISSUE THREAD

**Issue by kenjiO** [freeCodeCamp/pantry-for-good#97]
I don't know how useful this data is.  If we do keep it, it should be formatted in a more readable way and fix the functionality to edit it.

**Comment by jspaine** [comment]
Yeah it's pretty clunky. Also frequency seems to actually mean interval.

How about an input to select a single start date and change that column to be offset in weeks. If you wanted to send eg. two items alternate weeks you'd set their interval to 2 and first offset to 0, second offset to 1. If the interval is weekly offset should be disabled, if interval is 2 (fortnightly) offset should be 0 or 1... So max(offset) should be interval - 1.

Maybe it would be less confusing with words too, eg offset = second and fourth week, interval = fortnightly or offset = third week, interval = monthly. Wouldn't work for 3 week intervals though.

**Comment by yaseenshaik** [comment]
To solve some confusion, I think we need to  
* show start date as a single date 
* change frequency to interval in weeks or just show "Every" label. 
* get actual days of the week 

For example:
* Person 1 wants to donate every Friday: `days: [Friday], interval: 1` ("Every week")
* Person 2 wants to donate Monday and Wednesday every fortnight: `days:[Monday, Wednesday] interval: 2` ("Every Fortnight")

Similarly `interval: 4` would be "Every Month". This will cover all cases.

**Comment by jspaine** [comment]
It's a schedule for packing items for delivery, it's assumed there's one delivery a week. It could be nice if it was more flexible but it's another issue I think.

I'm not sure it needs any dates if you think of the interval as just every n deliveries., The start date column could be replaced with the offset into the cycle, and you could have a single control at the top to skip forward or backward in the cycle. I think this would make it easier to work with customizable delivery dates too.

**Comment by yaseenshaik** [comment]
Ok now I'm confused. Why do you assume only one delivery per week? Isn't
the list showing food items and not customers?

If it's just a schedule for packing, what does frequency stand for? And
what's the need for having a packing schedule. Isn't there something better
already?

**Comment by jspaine** [comment]
Yeah, sorry!

The app always assumed one delivery a week and we haven't changed that. I guess it's the most common scenario too.

The idea is that some items you might not want to send so regularly, so maybe non-perishable stuff like rice and pasta you could send every other week, while perishable stuff like milk you'd send every week.
